Repository NaughtyChas/ENGG1340-GP, pull requests merged in 2025-04, with the labels that each got.

#6 Add auto-build actions
  .github/workflows/buildExe.yml
Labels: Area: Compilation, Size: S, Area: CI/CD, Priority: 2

#2 Add ncurses installation script / add PATH
  .github/workflows/cppChecks.yml
  Makefile
  installNcurses.sh
  src/game.cpp
Labels: Area: Compilation, Size: S

#17 Update game main menu again
  .github/workflows/buildExe.yml
  include/game.h
  src/game.cpp
Labels: Size: M, Area: UI/UX, Area: Design, Priority: 1

#19 Implement In-game UI
  Makefile
  include/gameplay.h
  include/startGame.h
  src/game.cpp
  src/gameplay.cpp
  src/startGame.cpp
Labels: Size: M, Area: UI/UX, Area: Design, Priority: 0, Don't merge

#21 Player logic implementations
  include/gameplay.h
  src/game.cpp
  src/gameplay.cpp
  src/player.cpp
Labels: Area: Compilation, Area: Gamerule, Area: UI/UX, Area: Structure, Size: XL, Priority: 0
